# Generated by Django 5.2.15 on 2026-07-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_roadmapoptin_goal_category_goal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
