# Generated by Django 5.2.15 on 2026-07-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_problem_solution_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='milestone',
            field=models.IntegerField(default=1),
        ),
    ]
